apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  - plan-trip-product-1.0.0.yaml
  #- countries-product.yaml
  #- vehicle-info-product.yaml
  #- building-events-product.yaml
  #- mq-product.yaml
  #- rabbitmq-product.yaml
  #- datetime-product.yaml

patches:
  - target:
      kind: Product
    path: apic-creds.yaml