apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Generate ConfigMaps wrapping the OpenAPI and AsyncAPI
# files. API CR expects a configmap with 
# the API definition, this lets us keep the API definitions in source format.
configMapGenerator:
  - name: plan-trip_api-cm
    files:
      - plan-trip_api_1.0.0.yaml

generatorOptions:
  disableNameSuffixHash: true

resources:

 - products